GOENV: DEV
SRV_ITEM__DB_Host: 127.0.0.1
SRV_ITEM__DB_Password: "sincos"
SRV_ITEM__DB_SlaveHost: ""
SRV_ITEM__DB_User: "sincos"
SRV_ITEM__DefaultIface: "feth2575"
SRV_ITEM__ResPath: "/Users/sincos/sincos/tmp/item"
SRV_ITEM__Server_Debug: "true"
SRV_ITEM__Server_Port: "9999"
SRV_ITEM__MinioClient_Bucket: "item-manager"
SRV_ITEM__MinioClient_Endpoint: "127.0.0.1:9000"
SRV_ITEM__MinioClient_ExpiredDuration: "86400000000000"
SRV_ITEM__MinioClient_Location: "cn"
SRV_ITEM__MinioClient_AccessKey: "sincos"
SRV_ITEM__MinioClient_SecretKey: "sincospro"
SRV_ITEM__MinioClient_UseSSL: "false"
SRV_ITEM__MinioFwdPort: "9000"
